packages:
  - packages/*
  - modules/*
  - tools/*

catalog:
  chalk: ^5.4.1
  deepmerge-ts: ^7.1.3
  eslint: ^9.17.0
  execa: ^9.5.2
  fs-chain: ^8.2.4
  garou: ^0.8.3
  lodash: ^4.17.21
  settingz: ^0.2.0
  sort-keys: ^5.1.0
  typescript: ~5.7.2
  yaml: ^2.7.0
