packages:
  - packages/*
  - modules/*
  - tools/*

catalog:
  '@eslint/eslintrc': ^3.3.5
  '@eslint/js': ^9.39.4
  '@eslint/markdown': ^8.0.1
  '@vitest/ui': ^4.1.5
  chalk: ^5.6.2
  eslint: ^9.39.4
  eslint-plugin-vue: ^10.9.0
  execa: ^9.6.1
  fs-chain: ^10.0.0
  garou: ^0.9.21
  lodash: ^4.18.1
  settingz: ^0.2.0
  sort-keys: ^6.0.0
  stylelint: ^17.9.0
  typescript: ~6.0.3
  typescript-eslint: ^8.59.0
  vitest: ^4.1.5
  yaml: ^2.8.3

catalogs:
  overrides:
    eslint: ^9.39.4
    eslint-plugin-react-hooks: ^5.2.0
    globals: ^17.4.0
    prettier: ~3.8.3

configDependencies:
  pnpm-plugin-nice-move: 0.3.3+sha512-sZBCAirkIGqRpZRR4DtPnvUF2R6kNPT/mWT34L6pt4E/WjwrMk4TcE8S0X0sv69Y8L2rFNd3o2GTbaokwtZATw==

overrides:
  eslint: catalog:overrides
  eslint-plugin-react-hooks: catalog:overrides
  globals: catalog:overrides

patchedDependencies:
  '@commitlint/rules': .patches/@commitlint__rules.patch
  lint-staged: .patches/lint-staged.patch

trustPolicyExclude:
  - semver@6.3.1
  - '@pnpm/config'
