packages:
  - packages/*
  - modules/*
  - tools/*

catalog:
  '@eslint/eslintrc': ^3.3.3
  '@eslint/js': ^9.39.3
  '@eslint/markdown': ^7.5.1
  '@types/node': ^24.10.13
  '@vitest/ui': ^4.0.18
  chalk: ^5.6.2
  eslint: ^9.39.3
  eslint-plugin-vue: ^10.8.0
  execa: ^9.6.1
  fs-chain: ^10.0.0
  garou: ^0.9.17
  lodash: ^4.17.23
  settingz: ^0.2.0
  sort-keys: ^6.0.0
  stylelint: ^16.26.1
  typescript: ~5.9.3
  typescript-eslint: ^8.56.0
  vitest: ^4.0.18
  yaml: ^2.8.2

catalogs:
  overrides:
    eslint: ^9.39.2
    eslint-plugin-react-hooks: ^5.2.0
    globals: ^17.3.0
    prettier: ~3.8.1

configDependencies:
  pnpm-plugin-nice-move: 0.2.0+sha512-l2lUgbyXPStU80fF9szueoqh26htBxsBLZZ0CY6WngH1EaCSjMYhRFGxIIg282kN03Lr1EvvzYjdsltVq6J0tw==

overrides:
  eslint: catalog:overrides
  eslint-plugin-react-hooks: catalog:overrides
  globals: catalog:overrides

patchedDependencies:
  '@commitlint/rules': patches/@commitlint__rules.patch
  conventional-changelog-angular@8.1.0: patches/conventional-changelog-angular@8.1.0.patch
  lint-staged: patches/lint-staged.patch

trustPolicyExclude:
  - semver@6.3.1
  - '@pnpm/config'
