packages:
  - packages/*
  - modules/*
  - tools/*

catalog:
  '@eslint/eslintrc': ^3.3.6
  '@eslint/js': ^9.39.5
  '@eslint/markdown': ^8.0.3
  chalk: ^6.0.0
  deepmerge-ts: ^8.0.2
  eslint-plugin-vue: ^10.10.0
  execa: ^10.0.1
  fs-chain: ^10.0.0
  garou: ^0.9.21
  lodash: ^4.18.1
  settingz: ^0.2.0
  sort-keys: ^6.0.1
  stylelint: ^17.14.1
  typescript: ~6.0.3
  typescript-eslint: ^8.68.0
  yaml: ^2.9.0

catalogs:
  overrides:
    eslint: ^9.39.5
    eslint-plugin-react-hooks: ^5.2.0
    globals: ^17.11.0
    prettier: ~3.9.6
  vitest:
    '@vitest/ui': ^4.1.11
    vitest: ^4.1.11

configDependencies:
  pnpm-plugin-nice-move: 0.3.7+sha512-XmvMlOA/Zd26tv69MyOSC90isG1+APVs8k6D0hGxV/FFYipyKtToR4eYo+ueptlEGce3nDegg7kWnjDF6aXHUQ==

overrides:
  eslint: catalog:overrides
  eslint-plugin-react-hooks: catalog:overrides
  globals: catalog:overrides

patchedDependencies:
  '@commitlint/rules': .patches/@commitlint__rules.patch
  lint-staged: .patches/lint-staged.patch

trustPolicyExclude:
  - '@pnpm/config'
  - '@pnpm/types'
