packages:
  - packages/*
  - modules/*
  - tools/*

catalog:
  '@eslint/js': ^9.39.1
  '@eslint/eslintrc': ^3.3.3
  '@eslint/markdown': ^7.5.1
  '@types/node': ^24.10.1
  '@vitest/ui': ^4.0.15
  chalk: ^5.6.2
  eslint: ^9.39.1
  eslint-plugin-vue: ^10.6.2
  execa: ^9.6.1
  fs-chain: ^10.0.0
  garou: ^0.9.16
  lodash: ^4.17.21
  settingz: ^0.2.0
  sort-keys: ^6.0.0
  stylelint: ^16.26.1
  typescript: ~5.9.3
  typescript-eslint: ^8.48.1
  vitest: ^4.0.15
  yaml: ^2.8.2

catalogs:
  overrides:
    eslint-plugin-react-hooks: ^5.2.0
    eslint: ^9.39.1
    globals: ^16.5.0
    prettier: ~3.6.2

ignorePatchFailures: false

overrides:
  eslint: catalog:overrides
  eslint-plugin-react-hooks: catalog:overrides
  globals: catalog:overrides

patchedDependencies:
  '@commitlint/rules': patches/@commitlint__rules.patch
  conventional-changelog-angular@7.0.0: patches/conventional-changelog-angular@7.0.0.patch
  lint-staged: patches/lint-staged.patch

shamefullyHoist: true

verifyDepsBeforeRun: warn
