packages:
  - packages/*
  - modules/*
  - tools/*

catalog:
  '@eslint/js': ^9.18.0
  chalk: ^5.4.1
  eslint: ^9.20.1
  execa: ^9.5.2
  fs-chain: ^8.2.4
  garou: ^0.9.4
  globals: ^15.15.0
  lodash: ^4.17.21
  settingz: ^0.2.0
  sort-keys: ^5.1.0
  stylelint: ^16.14.1
  typescript: ~5.7.3
  yaml: ^2.7.0
