shamefullyHoist: true

overrides:
  eslint: 'catalog:'
  eslint-plugin-react-hooks: 'catalog:'
  globals: 'catalog:'

patchedDependencies:
  '@commitlint/rules': patches/@commitlint__rules.patch
  conventional-changelog-angular@7.0.0: patches/conventional-changelog-angular@7.0.0.patch
  lint-staged: patches/lint-staged.patch

packages:
  - packages/*
  - modules/*
  - tools/*

catalog:
  '@eslint/js': ^9.28.0
  chalk: ^5.4.1
  eslint: ^9.28.0
  execa: ^9.6.0
  fs-chain: ^10.0.0
  garou: ^0.9.8
  globals: ^16.2.0
  lodash: ^4.17.21
  settingz: ^0.2.0
  sort-keys: ^5.1.0
  stylelint: ^16.20.0
  typescript: ~5.8.3
  yaml: ^2.8.0
  eslint-plugin-react-hooks: ^5.2.0
