packages:
  - packages/*
  - modules/*
  - tools/*

catalog:
  '@eslint/js': ^9.27.0
  chalk: ^5.4.1
  eslint: ^9.27.0
  execa: ^9.5.3
  fs-chain: ^10.0.0
  garou: ^0.9.7
  globals: ^16.1.0
  lodash: ^4.17.21
  settingz: ^0.2.0
  sort-keys: ^5.1.0
  stylelint: ^16.19.1
  typescript: ~5.8.3
  yaml: ^2.8.0
  eslint-plugin-react-hooks: ^5.2.0
