packages:
  - packages/*
  - modules/*
  - tools/*

catalog:
  '@eslint/js': ^9.39.0
  chalk: ^5.6.2
  execa: ^9.6.0
  fs-chain: ^10.0.0
  garou: ^0.9.15
  lodash: ^4.17.21
  settingz: ^0.2.0
  sort-keys: ^6.0.0
  stylelint: ^16.25.0
  typescript: ~5.9.3
  yaml: ^2.8.1

catalogMode: prefer

catalogs:
  overrides:
    eslint: ^9.39.0
    eslint-plugin-react-hooks: ^5.2.0
    globals: ^16.5.0
    prettier: ~3.6.2

ignorePatchFailures: false

overrides:
  eslint: catalog:overrides
  eslint-plugin-react-hooks: catalog:overrides
  globals: catalog:overrides

patchedDependencies:
  '@commitlint/rules': patches/@commitlint__rules.patch
  conventional-changelog-angular@7.0.0: patches/conventional-changelog-angular@7.0.0.patch
  lint-staged: patches/lint-staged.patch

shamefullyHoist: true

verifyDepsBeforeRun: warn

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@bring-it/cli'
  - '@bring-it/npm'
  - '@typescript-eslint/*'
  - typescript-eslint
