packages:
  - packages/*
  - modules/*
  - tools/*

catalog:
  '@eslint/js': ^9.32.0
  chalk: ^5.5.0
  execa: ^9.6.0
  fs-chain: ^10.0.0
  garou: ^0.9.12
  lodash: ^4.17.21
  settingz: ^0.2.0
  sort-keys: ^5.1.0
  stylelint: ^16.23.1
  typescript: ~5.9.2
  yaml: ^2.8.1

catalogMode: prefer

catalogs:
  overrides:
    eslint: ^9.32.0
    eslint-plugin-react-hooks: ^5.2.0
    globals: ^16.3.0
    prettier: ~3.6.2

ignorePatchFailures: false

overrides:
  eslint: catalog:overrides
  eslint-plugin-react-hooks: catalog:overrides
  globals: catalog:overrides

patchedDependencies:
  '@commitlint/rules': patches/@commitlint__rules.patch
  conventional-changelog-angular@7.0.0: patches/conventional-changelog-angular@7.0.0.patch
  lint-staged: patches/lint-staged.patch

shamefullyHoist: true

verifyDepsBeforeRun: warn
