'use strict';

module.exports = {
  plugins: ['stylelint-order'],
  rules: {
    'order/properties-alphabetical-order': null,
    'order/properties-order': [
      [
        'composes',
        'all',
        // --------------
        'appearance',
        'visibility',
        'mix-blend-mode',
        'isolation',
        // --------------
        'display',
        'position',
        'z-index',
        'top',
        'right',
        'bottom',
        'left',
        // --------------
        'float',
        'clear',
        // --------------
        'flex',
        'flex-basis',
        'flex-direction',
        'flex-flow',
        'flex-grow',
        'flex-shrink',
        'flex-wrap',
        // --------------
        'align-content',
        'align-items',
        'align-self',
        'justify-content',
        'justify-items',
        'justify-self',
        'order',
        // --------------
        'grid',
        'grid-area',
        'grid-template',
        'grid-template-areas',
        'grid-template-rows',
        'grid-template-columns',
        'grid-row',
        'grid-row-start',
        'grid-row-end',
        'grid-column',
        'grid-column-start',
        'grid-column-end',
        'grid-auto-rows',
        'grid-auto-columns',
        'grid-auto-flow',
        'grid-gap',
        'grid-row-gap',
        'grid-column-gap',
        // --------------
        'columns',
        'column-gap',
        'column-fill',
        'column-rule',
        'column-rule-width',
        'column-rule-style',
        'column-rule-color',
        'column-span',
        'column-count',
        'column-width',
        // --------------
        'backface-visibility',
        'perspective',
        'perspective-origin',
        // --------------
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        // --------------
        'outline',
        'outline-offset',
        'outline-width',
        'outline-style',
        'outline-color',
        // --------------
        'border',
        'border-top',
        'border-right',
        'border-bottom',
        'border-left',
        // --------------
        'border-width',
        'border-top-width',
        'border-right-width',
        'border-bottom-width',
        'border-left-width',
        // --------------
        'border-style',
        'border-top-style',
        'border-right-style',
        'border-bottom-style',
        'border-left-style',
        // --------------
        'border-color',
        'border-top-color',
        'border-right-color',
        'border-bottom-color',
        'border-left-color',
        // --------------
        'border-image',
        'border-image-source',
        'border-image-width',
        'border-image-outset',
        'border-image-repeat',
        'border-image-slice',
        // --------------
        'border-radius',
        'border-top-left-radius',
        'border-top-right-radius',
        'border-bottom-left-radius',
        'border-bottom-right-radius',
        // --------------
        'filter',
        'opacity',
        'box-shadow',
        // --------------
        'background',
        'background-attachment',
        'background-clip',
        'background-color',
        'background-image',
        'background-origin',
        'background-position',
        'background-repeat',
        'background-size',
        'background-blend-mode',
        // --------------
        'box-sizing',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        // --------------
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        // --------------
        'overflow',
        'overflow-x',
        'overflow-y',
        'resize',
        // --------------
        'table-layout',
        'border-collapse',
        'border-spacing',
        'empty-cells',
        'writing-mode',
        'caption-side',
        // --------------
        'list-style',
        'list-style-type',
        'list-style-position',
        'list-style-image',
        // --------------
        'transform',
        'transform-origin',
        'transform-style',
        'transition',
        'transition-delay',
        'transition-duration',
        'transition-property',
        'transition-timing-function',
        // --------------
        'transition',
        'transition-delay',
        'transition-duration',
        'transition-property',
        'transition-timing-function',
        // --------------
        'animation',
        'animation-name',
        'animation-duration',
        'animation-timing-function',
        'animation-delay',
        'animation-iteration-count',
        'animation-direction',
        'animation-fill-mode',
        'animation-play-state',
        // --------------
        'direction',
        'hyphens',
        // --------------
        'vertical-align',
        'text-align',
        'text-align-last',
        'text-justify',
        'text-indent',
        'text-transform',
        'text-decoration',
        'text-decoration-color',
        'text-decoration-line',
        'text-decoration-style',
        'text-rendering',
        'text-shadow',
        'text-overflow',
        // --------------
        'line-height',
        'word-spacing',
        'letter-spacing',
        'tab-size',
        'white-space',
        'word-break',
        'word-wrap',
        'overflow-wrap',
        // --------------
        'color',
        // --------------
        'font',
        'font-family',
        'font-kerning',
        'font-size',
        'font-size-adjust',
        'font-stretch',
        'font-weight',
        'font-smoothing',
        'osx-font-smoothing',
        'font-variant',
        'font-style',
        // --------------
        'content',
        'quotes',
        'counter-reset',
        'counter-increment',
        // --------------
        'page-break-before',
        'page-break-after',
        'page-break-inside',
        // --------------
        'nav-index',
        'nav-up',
        'nav-right',
        'nav-down',
        'nav-left',
        // --------------
        'touch-action',
        'cursor',
        'pointer-events',
        'user-select',
        'speak',
        'will-change'
      ],
      {
        unspecified: 'bottomAlphabetical',
        emptyLineBeforeUnspecified: 'always',
        severity: 'warning'
      }
    ]
  }
};
